# Generated by Django 3.1.5 on 2021-12-15 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id1', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('type1', models.CharField(blank=True, max_length=256, null=True)),
                ('by', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id1', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, null=True)),
                ('type1', models.CharField(max_length=256)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('by', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('text', models.CharField(blank=True, max_length=256, null=True)),
                ('type1', models.CharField(blank=True, max_length=256, null=True)),
                ('by', models.CharField(blank=True, max_length=256, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
