# Generated by Django 3.1.5 on 2021-12-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='api',
            field=models.BooleanField(default=True),
        ),
    ]
